### ISSUE TITLE
Carnotaurus arms snap during trotting.

### ISSUE THREAD

**Issue by Kingjaffad** [TheIsleGame/bugs#230]
## Expected Behavior

Carnotaurus arms move with the trotting animation as intended.

## Current Behavior

During the trotting animation for both the Adult and Juvenile Carnotaurus, the arms will snap backwards at the end of each trot cycle.

Video evidence: https://www.youtube.com/watch?v=3Ip-6XsJ8kU (Adult)

https://www.youtube.com/watch?v=3ek9AElTvEM (Juvenile)
## Steps to reproduce

(1) Spawn as either the Adult Carnotaurus or the Juvenile.

(2) Begin to trot and the arms will seen snapping back into the chest as your Carnotaurus trots.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2065539/TheIsle.log)

> **Game Version:** 0.1.38.9 (Development)
> **Operating System**: Windows
> **Network Role**: Client

**Comment by foszor** [comment]
Fixed in 0.1.39.0

**Comment by oOCircleofLifeOo** [comment]
Issue is still occuring on the juvi Carno in build: 0.1.53.3. Fixed on the adult Carno.

**Comment by Hypno123** [comment]
Added to #501
