### ISSUE TITLE
Herbivore Scent animation can be skipped by Simultaneously holding A or D and Scent key.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#244]
## Expected Behavior

Herbivore Scent animation to not be skipped by Simultaneously holding A or D and scent key.

## Current Behavior

Herbivore Scent animation can be skipped by Simultaneously Holding A or D (Moving left or right) and scent key.
Player will get stuck in-place,Idle animation will be played,but still,scent objects will be highlighted.
Doesn't happen to carnivores.

Video Evidence:
https://youtu.be/CkNNIlwXdBU

Notes: 
if you try in a Listen server,the scent animation will be played.
Testing with Spire#5368 in the Dev Testing server and other players won't see the animation either.

## Steps to reproduce

-Spawn as any survival herbivore.
-Simultaneously hold A or D and Q (or your Scent key)
-Notice that you get stuck in place,idle animation will be played.
-If you don't get stuck,repeat second step until you get stuck in place. 3-4 tries should get you stuck.
-Keep holding A or D and Scent key
-Wait until Scent objects are highlighted.
-Notice that scent works,but the actual animation is skipped.

## Build Information

[TheIsle.log](https://github.com/TheIsleGame/bugs/files/2066462/TheIsle.log)

> **Game Version:**  0.1.38.9 ( development )

> **Operating System**: Windows 10

> **Network Role**: Client

**Comment by looterz** [comment]
I haven't been able to reproduce this, but I have reproduced and fixed the issue reported by @Cocazou above. This may have been fixed already due to other fixes related to scent and movement for 0.1.39.0

**Comment by Kingjaffad** [comment]
Issue is still present in game version 0.1.53.3

I was able to recreate this issue with all four of the movement keys, with the scent key, not just the A and D keys.
