### ISSUE TITLE
Allosaurus unable to eat medium gore piles

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#286]
## Expected Behavior

Unsure if this is intended. 

Every other species in Allo's tier can eat from medium gore piles, so you would expect them to be able to as well.

## Current Behavior

The Allosaurus is unable to eat from medium sized gore piles, whilst all other species in its tier can.

## Steps to reproduce

1. Spawn as Allosaurus on test level.
2. Attempt to eat from medium size gore pile and find you are unable to.
3. Switch to Cerato and be able to eat from the gore pile.

## Build Information

> **Game Version:** 0.1.39.9 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by looterz** [comment]
Fixed in 0.1.40.0

**Comment by Aliens218** [comment]
This is still an issue.

**Comment by PCSly** [comment]
Can confirm this is still an issue. As a 1.0 Adult Allosaurus medium gore piles cannot be eaten.

**Comment by Hypno123** [comment]
Fixed.
