### ISSUE TITLE
Carnivore's body freezes if scent is used during movement-idle transition.

### ISSUE THREAD

**Issue by ExtraHu3** [TheIsleGame/bugs#419]
## Expected Behavior

Scent Animation to play properly when scent is used during movement to idle transition.

## Current Behavior

Scent Animation is not played properly if scent is used during movement to idle transition.
Result is an awkward Frozen idle.
Exclusive to carnivores.
Easier to reproduce as: Giga and Rex (due to momentum, the movement to idle transition takes longer).
Easier to notice as: Utah and Dilo.
Harder to notice as: Cerato and Allo.

Video Evidence: https://youtu.be/aBC_TvSfabY

Possibly intended to avoid awkward sliding during animation transition.
Tested on both Listen and Dedicated Servers.
Seemed to be easier to reproduce at higher frame rates.

## Steps to reproduce

1.Select any Carnivore.
2.Move.
3.Stop moving and **immediately** use scent.
4.Notice that the scent animation won't play properly.

## Build Information

> **Game Version:** 0.1.51.2 ( development )

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed.

**Comment by Emanthealmighty** [comment]
I tried it for the majority of the dinosaurs, even with some carnivores that aren't even in survival, and it worked properly... but it seems that dilophosaurus and utahraptor still freeze up when they use the smell animation. Sorry for the false claim!

**Comment by dinosauriac** [comment]
I don't really see the problem here? If you're not walking you won't be doing the mobile scent animation, it'll switch to the standing animation. Pressing the key when you're only like 20% of the way through the movement transition will of course put you back to being in idle. If that's the freezing up you're talking about, it's a largely unavoidable quirk of having this ability available in both movement modes.

**Comment by Emanthealmighty** [comment]
I know that the sub rex, juvi rex and sucho don't have this problem... wouldn't it be possible to set the mobile sniff animation the same way it is set up for them for all the other dinosaurs? @dinosauriac
