### ISSUE TITLE
Utahraptor plays incorrect idle animation when biting/roaring.

### ISSUE THREAD

**Issue by Hypno123** [TheIsleGame/bugs#89]
## Expected Behavior

Utah should not attempt to play the incorrect idle animation when biting/roaring whilst stationary.

## Current Behavior

Utah (all stages) plays the incorrect idle animation when you bite or roar and are stationary.

## Steps to reproduce

1. Spawn as Utah (any stage of the lifecycle.)
2. Jump.
3. Bite whilst falling and see idle animation play (look at legs.)

This occurs for all stages and can happen when stationary, jumping, crouching and swimming.

## Build Information

> **Game Version:** 0.1.36.8 (dev)

> **Operating System**: Windows

> **Network Role**: Client

**Comment by Hypno123** [comment]
Fixed in 0.1.36.9

**Comment by ExtraHu3** [comment]
Apparently this issue is back at 0.1.37.0 (development)

Video Evidence:
https://youtu.be/g_1Ta12-83g
